### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by Jadvviga** [maciejdrobnik/Team2_CMS#35]

**Comment by Jadvviga** [comment]
editing/deleting on edit page

**Comment by Jadvviga** [comment]
add new folder/add new page
super admin can delete/add roots, normal users cant
user can delete category (folder with pages) but there should be wraning

**Comment by Jadvviga** [comment]
there should be warning when deleting

**Comment by Jadvviga** [comment]
add pop ups for adding/deleting/saving stuff ('page saved')

**Comment by Jadvviga** [comment]
warning ehrn you leave editor withous saves

**Comment by Jadvviga** [comment]
editing folders

**Comment by Jadvviga** [comment]
delet unessesary symbols in editor

**Comment by Jadvviga** [comment]
editing names of roots

**Comment by maciejdrobnik** [comment]
Everything is ready

**Comment by maciejdrobnik** [comment]
Everything is ready
