### ISSUE TITLE
Styling pages

### ISSUE THREAD

**Issue by Jadvviga** [maciejdrobnik/Team2_CMS#36]

**Comment by Jadvviga** [comment]
styles for tags list

**Comment by Jadvviga** [comment]
make folder link diffrent then page link

**Comment by Jadvviga** [comment]
style for adding window (width)

**Comment by maciejdrobnik** [comment]
> window for editing/deleting window

I don't know how to fix this

**Comment by maciejdrobnik** [comment]
Finished
