### ISSUE TITLE
Most important

### ISSUE THREAD

**Issue by maciejdrobnik** [maciejdrobnik/Team2_CMS#57]

**Comment by maciejdrobnik** [comment]
Tags: list of tags in page.html

**Comment by maciejdrobnik** [comment]
Whole edit box in page.html:
-edit name works fine but for longer names looks awful
-buttons, in my opinion list form is ok but styling of buttons needs to be different 
-border, it may be good idea but for now it look terrible

**Comment by maciejdrobnik** [comment]
edit folder: editfolderdialog component:
-Edit name is ok I think
-list of tags should be the same as in page. html or at least similar
-My idea for the list is to give it borders but with white background it looks bad.
-buttons styling is ok. I woud leave it like that
-input styling should be changed
-it should be bigger gap between input and add tag
-consider what to show when it is no tag( for now it is text and I would leave it but its place seems not perfect)

**Comment by maciejdrobnik** [comment]
add page and add folder input styling:
whole dialog seems ok apart from input field.
If you have idea how to improve other elements feel free to do so

**Comment by maciejdrobnik** [comment]
confirm exiting editor without saving changes(I forgot about that but it is doable and nice feature)

**Comment by maciejdrobnik** [comment]
Close button grey background(I don't know how to name it)

**Comment by maciejdrobnik** [comment]
Both master and master editor:
Content and edit panels shouldn't be so close to header

**Comment by Jadvviga** [comment]
> edit folder: editfolderdialog component: -Edit name is ok I think -list of tags should be the same as in page. html or at least similar -My idea for the list is to give it borders but with white background it looks bad. -buttons styling is ok. I woud leave it like that -input styling should be changed -it should be bigger gap between input and add tag -consider what to show when it is no tag( for now it is text and I would leave it but its place seems not perfect)

its now partly changed on Master with tags there added, i will aslo take care of styles of it on editor

**Comment by Jadvviga** [comment]
> Whole edit box in page.html: -edit name works fine but for longer names looks awful -buttons, in my opinion list form is ok but styling of buttons needs to be different -border, it may be good idea but for now it look terrible -Oskar wanted it to be "sticky" but for now it is position: fixed

its now partly changed on Master with tags there added, i will aslo take care of styles of it on editor

**Comment by Jadvviga** [comment]
> Close button grey background(I don't know how to name it)

done

**Comment by maciejdrobnik** [comment]
Great job. Everything is done and looks great
